services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ipgeo-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - ipgeo-net
    deploy:
      resources:
        limits:
          memory: 3g    
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$SA_PASSWORD\" -Q \"SELECT 1\" -C || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s

  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: ipgeo-api
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=IpGeoDb;User Id=sa;Password=${SQL_SA_PASSWORD};TrustServerCertificate=True;
      - IpGeoProvider__BaseUrl=https://freegeoip.app/
    ports:
      - "5000:8080"
    networks:
      - ipgeo-net

networks:
  ipgeo-net:
    driver: bridge